"""add_aircraft_table

Revision ID: ca281e8bedd2
Revises: ac9bb4b6e929
Create Date: 2026-03-11 14:18:03.865786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca281e8bedd2'
down_revision: Union[str, Sequence[str], None] = 'ac9bb4b6e929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('icao24', sa.String(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('baro_altitude', sa.Float(), nullable=True),
    sa.Column('on_ground', sa.Boolean(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('true_track', sa.Float(), nullable=True),
    sa.Column('last_contact', sa.Integer(), nullable=True),
    sa.Column('trail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('icao24')
    )
    op.drop_constraint(op.f('satellites_norad_cat_id_key'), 'satellites', type_='unique')
    op.drop_index(op.f('ix_satellites_norad_cat_id'), table_name='satellites')
    op.create_index(op.f('ix_satellites_norad_cat_id'), 'satellites', ['norad_cat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellites_norad_cat_id'), table_name='satellites')
    op.create_index(op.f('ix_satellites_norad_cat_id'), 'satellites', ['norad_cat_id'], unique=False)
    op.create_unique_constraint(op.f('satellites_norad_cat_id_key'), 'satellites', ['norad_cat_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('aircraft')
    # ### end Alembic commands ###
